name: PlayerPlus
main: com.almuramc.playerplus.PlayerPlus
version: 1.2
authors: [AlmuraDev]
depend: [Spout]
permissions:
    playerplus.*:
        description: 给予PlayerPlus的全部使用权限
        children:
            playerplus.use: true
            playerplus.use.bracelet: true
            playerplus.use.ears: true
            playerplus.use.sunglasses: true
            playerplus.use.tail: true
            playerplus.use.tophat: true
            playerplus.use.notchhat: true
            playerplus.use.wings: true
            playerplus.use.capes: true
    playerplus.use:
        description: 允许用户使用 PlayerPlus 接口
        default: op    
    playerplus.use.bracelet:
        description: 允许手镯
        default: op
    playerplus.use.ears:
        description: 允许耳环
        default: op
    playerplus.use.sunglasses:
        description: 允许墨镜
        default: op
    playerplus.use.tail:
        description: 允许尾巴
        default: op
    playerplus.use.tophat:
        description: 允许帽子
        default: op
    playerplus.use.notchhat:
        description: 允许Notch帽子
        default: op        
    playerplus.use.wings:
        description: 允许翅膀
        default: op
    playerplus.title:
        description: 允许标题
        default: op
    playerplus.use.capes:
        description: 允许披风
        default: op    